### ISSUE TITLE
Missing connection problem and a unsafe pull connection

### ISSUE THREAD

**Issue by jwspencer** [jmlzone/PiPtr#22]
1. R504 and R506 have a floating Pin. They are connected to U503 pins 1 (DPO) and pin 2 (DMO).

2. U503	TUSB2036	Pin 6 is an I/O pin (EEDATA) and should not be tied to +3.3VDC. A software/firmware error could cause the chip to fail.

**Comment by n1ist** [comment]
1. R504 and R506 connections are waiting for me to pick a USB connector.  I'll do this when I get closer to finishing up the layout.

2.  I have added the pullup.  When EXTMEM is pulled up, EEDATA/~GANGED is only an input; it's hard-tied on TI's eval board as well.  A pullup will make it safer, however.
